# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f3055a0563ebae71556054a835e0a774"
name = "Price Breackup"
application_url = "https://handbook-eclipse-fable.ngrok-free.dev"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://handbook-eclipse-fable.ngrok-free.dev/auth/callback"
]
